"use client";
import { FormEvent,useEffect,useState } from "react";
import { Activity,Bot,Check,CircleAlert,Copy,Gauge,Globe2,History,Leaf,LoaderCircle,Search,ShieldCheck,Sparkles,Target,WandSparkles } from "lucide-react";
import type { AnalysisResult,Category,GenerateRequest } from "@/types/analyze";

type Tab="scan"|"report"|"studio"|"history";
type Saved={url:string;score:number;date:string};
const cats:Category[]=["SEO","GEO","AEO","Performance"];
const names:Record<Category,string>={SEO:"SEO",GEO:"GEO",AEO:"AEO",Performance:"ביצועים"};
const keys={SEO:"seo",GEO:"geo",AEO:"aeo",Performance:"performance"} as const;

export default function Home(){
 const [tab,setTab]=useState<Tab>("scan"),[url,setUrl]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<AnalysisResult|null>(null),[saved,setSaved]=useState<Saved[]>([]),[generated,setGenerated]=useState(""),[copy,setCopy]=useState(false);
 const [form,setForm]=useState<GenerateRequest>({type:"article",keyword:"",audience:"",tone:"מקצועי וברור",language:"עברית",analysis:null});
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem("organo-history")||"[]"))}catch{}},[]);
 async function scan(e:FormEvent){e.preventDefault();if(!url.trim())return setError("יש להזין כתובת אתר");setBusy(true);setError("");try{const session=localStorage.getItem("organo-session")||crypto.randomUUID();localStorage.setItem("organo-session",session);const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url,sessionId:session})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d);setForm(x=>({...x,analysis:d,keyword:d.topKeywords.slice(0,3).join(" ")}));const list=[{url:d.finalUrl,score:d.scores.overall,date:d.fetchedAt},...saved.filter(x=>x.url!==d.finalUrl)].slice(0,20);setSaved(list);localStorage.setItem("organo-history",JSON.stringify(list));setTab("report")}catch(x){setError(x instanceof Error?x.message:"הניתוח נכשל")}finally{setBusy(false)}}
 async function generate(){setBusy(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,analysis:result})});const d=await r.json();if(!r.ok)throw new Error(d.error);setGenerated(d.text)}catch(x){setError(x instanceof Error?x.message:"יצירת התוכן נכשלה")}finally{setBusy(false)}}
 async function copyText(text:string){await navigator.clipboard.writeText(text);setCopy(true);setTimeout(()=>setCopy(false),1400)}
 return <div className="app"><aside><div className="brand"><span><Leaf/></span><div><b>אורגנו</b><small>Organic Growth OS</small></div></div><nav><button className={tab==="scan"?"on":""} onClick={()=>setTab("scan")}><Search/>ניתוח אתר</button><button disabled={!result} className={tab==="report"?"on":""} onClick={()=>setTab("report")}><Activity/>דו״ח</button><button className={tab==="studio"?"on":""} onClick={()=>setTab("studio")}><WandSparkles/>סטודיו תוכן</button><button className={tab==="history"?"on":""} onClick={()=>setTab("history")}><History/>היסטוריה</button></nav><div className="tip"><Sparkles/><b>עיקרון אורגנו</b><p>תשובה ברורה, מקור אמין, ישות מזוהה ומבנה סמנטי משרתים גם חיפוש רגיל וגם מנועי AI.</p></div><small className="status"><i/> Vercel פעיל · Supabase ממתין לחיבור</small></aside>
 <main><header><div><small>מערכת צמיחה אורגנית חכמה</small><h1>אורגנו - SEO, GEO ו-AEO במקום אחד</h1></div><span><ShieldCheck/> סריקה מאובטחת</span></header>{error&&<div className="error" role="alert"><CircleAlert/>{error}</div>}
 {tab==="scan"&&<><section className="hero glass"><div className="eyebrow"><Leaf/> ניתוח 360° לאתר</div><h2>האם האתר שלך מובן גם לגוגל וגם לבינה מלאכותית?</h2><p>הדבק כתובת URL וקבל אבחון טכני, ציונים נפרדים, סדר עדיפויות ותוכן מוכן ליישום.</p><form onSubmit={scan}><div><Globe2/><input type="url" dir="ltr" aria-label="כתובת האתר לניתוח" autoComplete="url" spellCheck={false} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.example.co.il"/></div><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Search/>} נתח SEO · GEO · AEO</button></form><div className="trust"><span><Check/> robots ו-sitemap</span><span><Check/> Schema ותוכן</span><span><Check/> סורקי AI</span><span><Check/> ביצועים</span></div></section><section className="features">{[[<Search/>,"SEO","אינדוקס, canonical, כותרות, קישורים ותוכן"],[<Bot/>,"GEO","ישות, מקורות, מחבר ונגישות למנועי AI"],[<Target/>,"AEO","שאלות, תשובות קצרות, FAQ ומבנה לציטוט"],[<Gauge/>,"ביצועים","זמן תגובה, HTML, תמונות וסקריפטים"]].map((x,i)=><article className="glass" key={i}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section></>}
 {tab==="report"&&result&&<><section className="reportTitle"><div><small>הסריקה הושלמה</small><h2>{result.snapshot.title||result.finalUrl}</h2><p dir="ltr">{result.finalUrl}</p></div><div className="overall"><b>{result.scores.overall}</b><span>ציון אורגנו</span></div></section><section className="scores">{cats.map(c=><article className="glass" key={c}><span>{names[c]}</span><b>{result.scores[keys[c]]}</b><i><em style={{width:`${result.scores[keys[c]]}%`}}/></i></article>)}</section><section className="report"><div className="checks">{result.checks.map(x=><article className={`glass ${x.status}`} key={x.id}><span>{x.status==="pass"?<Check/>:<CircleAlert/>}</span><div><small>{names[x.category]} · {x.score}/100</small><h3>{x.title}</h3><p>{x.finding}</p><b>מה לעשות: {x.recommendation}</b></div></article>)}</div><aside className="facts"><article className="glass"><h3><Bot/> נגישות לסורקים</h3><p>Googlebot <b>{result.crawlability.googlebot}</b></p><p>OAI-SearchBot <b>{result.crawlability.oaiSearchBot}</b></p><p>GPTBot <b>{result.crawlability.gptBot}</b></p><p>Sitemap <b>{result.crawlability.sitemapFound?"נמצא":"לא נמצא"}</b></p></article><article className="glass"><h3><Activity/> תמונת מצב</h3><div className="metrics"><span><b>{result.snapshot.wordCount}</b>מילים</span><span><b>{result.snapshot.h1.length}</b>H1</span><span><b>{result.snapshot.images}</b>תמונות</span><span><b>{result.snapshot.schemaTypes.length}</b>Schema</span></div></article><button onClick={()=>setTab("studio")}><WandSparkles/> צור תוכן מהדו״ח</button></aside></section></>}
 {tab==="studio"&&<section><div className="sectionHead"><small>סטודיו התוכן</small><h2>הפוך את האבחון לתוכן מוכן</h2></div><div className="studio"><form className="glass" onSubmit={e=>{e.preventDefault();generate()}}><label>סוג תוכן<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as GenerateRequest["type"]})}><option value="article">מבנה מאמר</option><option value="faq">שאלות ותשובות</option><option value="meta">Title ו-Meta</option><option value="hero">פתיח לעמוד</option><option value="about">עמוד אודות</option><option value="schema">Schema</option></select></label><label>נושא<input value={form.keyword} onChange={e=>setForm({...form,keyword:e.target.value})}/></label><label>קהל יעד<input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><button disabled={busy}><Sparkles/> צור תוכן</button></form><article className="glass output"><div><h3>התוצאה</h3>{generated&&<button onClick={()=>copyText(generated)}><Copy/>{copy?"הועתק":"העתק"}</button>}</div>{generated?<pre>{generated}</pre>:<p>התוכן שייווצר יופיע כאן.</p>}</article></div>{result?.contentIdeas?.length?<div className="ideas">{result.contentIdeas.map((x,i)=><article className="glass" key={i}><small>{x.type}</small><h3>{x.title}</h3><p>{x.reason}</p><pre>{x.value}</pre><button onClick={()=>copyText(x.value)}><Copy/> העתק</button></article>)}</div>:null}</section>}
 {tab==="history"&&<section><div className="sectionHead"><small>מעקב אחר שיפור</small><h2>היסטוריית סריקות</h2></div><div className="history">{saved.length?saved.map((x,i)=><article className="glass" key={i}><Globe2/><div><h3>{new URL(x.url).hostname}</h3><p dir="ltr">{x.url}</p><small>{new Date(x.date).toLocaleString("he-IL")}</small></div><b>{x.score}</b><button onClick={()=>{setUrl(x.url);setTab("scan")}}>סרוק שוב</button></article>):<article className="glass empty"><History/><h3>עדיין אין סריקות</h3><p>הסריקה הראשונה תישמר כאן.</p></article>}</div></section>}
 <footer>אורגנו · תוכנן ונבנה עבור גיא רוזנברג 2026</footer></main></div>
}
