"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { Activity,Bot,Check,CircleAlert,Copy,Gauge,Globe2,History,Leaf,LoaderCircle,Search,ShieldCheck,Sparkles,Target,WandSparkles } from "lucide-react";
import type { AnalysisResult,Category,GenerateRequest } from "@/types/analyze";

type Tab="scan"|"report"|"studio"|"history";
type Saved={url:string;score:number;date:string};
const cats:Category[]=["SEO","GEO","AEO","Performance"];
const names:Record<Category,string>={SEO:"SEO",GEO:"GEO",AEO:"AEO",Performance:"ביצועים"};
const keys={SEO:"seo",GEO:"geo",AEO:"aeo",Performance:"performance"} as const;
const sourceNames:Record<AnalysisResult["response"]["source"],string>={direct:"קריאה ישירה", "browser-retry":"ניסיון דפדפן",reader:"Reader מרונדר",proxy:"Proxy ציבורי",pagespeed:"Google Lighthouse",blocked:"האתר חסם את כל מקורות הבדיקה"};
function limitedMessage(result:AnalysisResult){if(result.response.source==="blocked")return "האתר חסם את כל מקורות הקריאה החיצוניים. מוצג דו״ח חסימה מעשי בלבד, ללא בדיקת HTML, תוכן או ביצועים מלאה.";if(result.response.source==="pagespeed")return "האתר חסם סריקה ישירה. מוצג דו״ח מוגבל המבוסס על Google Lighthouse, ולכן בדיקות התוכן, GEO ו-AEO חלקיות.";return "האתר חסם סריקה ישירה. אורגנו הפעילה מקור קריאה חלופי. חלק מבדיקות השרת, התוכן או הביצועים עשויות להיות מוגבלות."}

export default function Home(){
 const [tab,setTab]=useState<Tab>("scan"),[url,setUrl]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<AnalysisResult|null>(null),[saved,setSaved]=useState<Saved[]>([]),[generated,setGenerated]=useState(""),[copy,setCopy]=useState(false),[generationMode,setGenerationMode]=useState<"ai"|"template"|"">(""),[backend,setBackend]=useState("בודק חיבור נתונים...");
 const [form,setForm]=useState<GenerateRequest>({type:"article",keyword:"",audience:"",tone:"מקצועי וברור",language:"עברית",analysis:null});
 useEffect(()=>{let local:Saved[]=[];try{local=JSON.parse(localStorage.getItem("organo-history")||"[]");setSaved(local)}catch{}const session=localStorage.getItem("organo-session")||crypto.randomUUID();localStorage.setItem("organo-session",session);fetch("/api/status").then(r=>r.json()).then(async d=>{const connected=Boolean(d?.supabase?.connected);setBackend(connected?"Supabase מחובר":"היסטוריה מקומית בלבד");if(connected){const r=await fetch(`/api/history?sessionId=${encodeURIComponent(session)}`);const h=await r.json();const cloud:Saved[]=(h.items||[]).map((x:{final_url?:string;url:string;overall_score:number;created_at:string})=>({url:x.final_url||x.url,score:x.overall_score,date:x.created_at}));const merged=[...cloud,...local.filter(x=>!cloud.some(c=>c.url===x.url))].slice(0,20);setSaved(merged)}}).catch(()=>setBackend("היסטוריה מקומית בלבד"))},[]);
 async function scan(e:FormEvent){e.preventDefault();if(!url.trim())return setError("יש להזין כתובת אתר");setBusy(true);setError("");try{const session=localStorage.getItem("organo-session")||crypto.randomUUID();localStorage.setItem("organo-session",session);const r=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url,sessionId:session})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d);setForm(x=>({...x,analysis:d,keyword:d.topKeywords.slice(0,3).join(" ")}));const list=[{url:d.finalUrl,score:d.scores.overall,date:d.fetchedAt},...saved.filter(x=>x.url!==d.finalUrl)].slice(0,20);setSaved(list);localStorage.setItem("organo-history",JSON.stringify(list));setTab("report")}catch(x){setError(x instanceof Error?x.message:"הניתוח נכשל")}finally{setBusy(false)}}
 async function generate(){setBusy(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,analysis:result})});const d=await r.json();if(!r.ok)throw new Error(d.error);setGenerated(d.text);setGenerationMode(d.mode||"template")}catch(x){setError(x instanceof Error?x.message:"יצירת התוכן נכשלה")}finally{setBusy(false)}}
 async function copyText(text:string){await navigator.clipboard.writeText(text);setCopy(true);setTimeout(()=>setCopy(false),1400)}
 return <div className="app"><aside><div className="brand"><span><Leaf aria-hidden="true"/></span><div><b>אורגנו</b><small>Organic Growth OS</small></div></div><nav aria-label="ניווט במערכת"><button className={tab==="scan"?"on":""} onClick={()=>setTab("scan")}><Search aria-hidden="true"/>ניתוח אתר</button><button disabled={!result} className={tab==="report"?"on":""} onClick={()=>setTab("report")}><Activity aria-hidden="true"/>דו״ח</button><button className={tab==="studio"?"on":""} onClick={()=>setTab("studio")}><WandSparkles aria-hidden="true"/>סטודיו תוכן</button><button className={tab==="history"?"on":""} onClick={()=>setTab("history")}><History aria-hidden="true"/>היסטוריה</button></nav><div className="tip"><Sparkles aria-hidden="true"/><b>עיקרון אורגנו</b><p>תשובה ברורה, מקור אמין, ישות מזוהה ומבנה סמנטי משרתים גם חיפוש רגיל וגם מנועי AI.</p></div><small className="status"><i/> Vercel פעיל · {backend}</small></aside>
 <main><header><div><small>מערכת צמיחה אורגנית חכמה</small><h1>אורגנו - SEO, GEO ו-AEO במקום אחד</h1></div><span><ShieldCheck aria-hidden="true"/> סריקה מאובטחת</span></header>{error&&<div className="error" role="alert"><CircleAlert aria-hidden="true"/>{error}</div>}
 {tab==="scan"&&<><section className="hero glass"><div className="eyebrow"><Leaf aria-hidden="true"/> ניתוח 360° לאתר</div><h2>האם האתר שלך מובן גם לגוגל וגם לבינה מלאכותית?</h2><p>הדבק כתובת URL וקבל אבחון טכני, ציונים נפרדים, סדר עדיפויות ותוכן מוכן ליישום.</p><form onSubmit={scan}><div><Globe2 aria-hidden="true"/><input type="url" dir="ltr" aria-label="כתובת האתר לניתוח" autoComplete="url" spellCheck={false} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.example.co.il"/></div><button disabled={busy}>{busy?<LoaderCircle className="spin" aria-hidden="true"/>:<Search aria-hidden="true"/>} נתח SEO · GEO · AEO</button></form><div className="trust"><span><Check aria-hidden="true"/> robots ו-sitemap</span><span><Check aria-hidden="true"/> Schema ותוכן</span><span><Check aria-hidden="true"/> סורקי AI</span><span><Check aria-hidden="true"/> ביצועים</span></div></section><section className="features">{[[<Search key="s"/>,"SEO","אינדוקס, canonical, כותרות, קישורים ותוכן"],[<Bot key="b"/>,"GEO","ישות, מקורות, מחבר ונגישות למנועי AI"],[<Target key="t"/>,"AEO","שאלות, תשובות קצרות, FAQ ומבנה לציטוט"],[<Gauge key="g"/>,"ביצועים","זמן תגובה, HTML, תמונות וסקריפטים"]].map((x,i)=><article className="glass" key={i}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section></>}
 {tab==="report"&&result&&<><section className="reportTitle"><div><small>הסריקה הושלמה</small><h2>{result.snapshot.title||result.finalUrl}</h2><p dir="ltr">{result.finalUrl}</p></div><div className="overall"><b>{result.scores.overall}</b><span>ציון אורגנו</span></div></section>{result.response.limited&&<div className="limited-notice" role="status"><b>בדיקה מוגבלת.</b> {limitedMessage(result)}</div>}<section className="scores">{cats.map(c=><article className="glass" key={c}><span>{names[c]}</span><b>{result.scores[keys[c]]}</b><i><em style={{width:`${result.scores[keys[c]]}%`}}/></i></article>)}</section><section className="report"><div className="checks">{result.checks.map(x=><article className={`glass ${x.status}`} key={x.id}><span>{x.status==="pass"?<Check aria-hidden="true"/>:<CircleAlert aria-hidden="true"/>}</span><div><small>{names[x.category]} · {x.score}/100</small><h3>{x.title}</h3><p>{x.finding}</p><b>מה לעשות: {x.recommendation}</b></div></article>)}</div><aside className="facts"><article className="glass"><h3><Bot aria-hidden="true"/> נגישות לסורקים</h3><p>Googlebot <b>{result.crawlability.googlebot}</b></p><p>OAI-SearchBot <b>{result.crawlability.oaiSearchBot}</b></p><p>GPTBot <b>{result.crawlability.gptBot}</b></p><p>Sitemap <b>{result.crawlability.sitemapFound?"נמצא":"לא נמצא"}</b></p><p>אופן קריאה <b>{sourceNames[result.response.source]}</b></p></article><article className="glass"><h3><Activity aria-hidden="true"/> תמונת מצב</h3><div className="metrics"><span><b>{result.snapshot.wordCount}</b>מילים</span><span><b>{result.snapshot.h1.length}</b>H1</span><span><b>{result.snapshot.images}</b>תמונות</span><span><b>{result.snapshot.schemaTypes.length}</b>Schema</span></div></article><button onClick={()=>setTab("studio")}><WandSparkles aria-hidden="true"/> צור תוכן מהדו״ח</button></aside></section></>}
 {tab==="studio"&&<section><div className="sectionHead"><small>סטודיו התוכן</small><h2>הפוך את האבחון לתוכן מוכן</h2></div><div className="studio"><form className="glass" onSubmit={e=>{e.preventDefault();generate()}}><label>סוג תוכן<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as GenerateRequest["type"]})}><option value="article">מבנה מאמר</option><option value="faq">שאלות ותשובות</option><option value="meta">Title ו-Meta</option><option value="hero">פתיח לעמוד</option><option value="about">עמוד אודות</option><option value="schema">Schema</option></select></label><label>נושא<input value={form.keyword} onChange={e=>setForm({...form,keyword:e.target.value})}/></label><label>קהל יעד<input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><button disabled={busy}><Sparkles aria-hidden="true"/> צור תוכן</button></form><article className="glass output"><div><h3>התוצאה {generationMode&&<small>· {generationMode==="ai"?"נוצר באמצעות AI":"נוצר מתבנית מקומית"}</small>}</h3>{generated&&<button onClick={()=>copyText(generated)}><Copy aria-hidden="true"/>{copy?"הועתק":"העתק"}</button>}</div>{generated?<pre>{generated}</pre>:<p>התוכן שייווצר יופיע כאן.</p>}</article></div>{result?.contentIdeas?.length?<div className="ideas">{result.contentIdeas.map((x,i)=><article className="glass" key={i}><small>{x.type}</small><h3>{x.title}</h3><p>{x.reason}</p><pre>{x.value}</pre><button onClick={()=>copyText(x.value)}><Copy aria-hidden="true"/> העתק</button></article>)}</div>:null}</section>}
 {tab==="history"&&<section><div className="sectionHead"><small>מעקב אחר שיפור</small><h2>היסטוריית סריקות</h2></div><div className="history">{saved.length?saved.map((x,i)=><article className="glass" key={i}><Globe2 aria-hidden="true"/><div><h3>{new URL(x.url).hostname}</h3><p dir="ltr">{x.url}</p><small>{new Date(x.date).toLocaleString("he-IL")}</small></div><b>{x.score}</b><button onClick={()=>{setUrl(x.url);setTab("scan")}}>סרוק שוב</button></article>):<article className="glass empty"><History aria-hidden="true"/><h3>עדיין אין סריקות</h3><p>הסריקה הראשונה תישמר כאן.</p></article>}</div></section>}
 <footer><div>אורגנו · תוכנן ונבנה על ידי גיא רוזנברג 2026<div className="legal-links"><Link href="/about">אודות</Link><Link href="/privacy">פרטיות</Link><Link href="/accessibility">נגישות</Link><Link href="/security">אבטחה</Link><Link href="/terms">תנאי שימוש</Link></div></div></footer></main></div>
}
